In [1]:
a, b = df.shape
inc = a //5


c = inc*1
d = inc*2
e = inc*3
f = inc*4
g = inc*5

df[0:c].to_csv('data/hn_cleaned_ready_for_bert_1.csv',index=False)
df[c:d].to_csv('data/hn_cleaned_ready_for_bert_2.csv',index=False)
df[d:e].to_csv('data/hn_cleaned_ready_for_bert_3.csv',index=False)
df[e:f].to_csv('data/hn_cleaned_ready_for_bert_4.csv',index=False)
df[f:].to_csv('data/hn_cleaned_ready_for_bert_5.csv',index=False)

NameError: name 'df' is not defined

In [2]:
df.head()

NameError: name 'df' is not defined

In [ ]:
df[["id", "comment_text"]] = df[["commentid", "cleaned_comment"]]
df = df[["id", "comment_text"]]

In [ ]:
df.head()

In [ ]:
%%time
df.to_csv('data/hn_cleaned_ready_for_bert.csv',index=False)

In [ ]:
df.shape

In [ ]:
a, b = df.shape

In [ ]:
a/2

In [ ]:
inc = a //5
print(inc*1)
print(inc*2)
print(inc*3)
print(inc*4)
print(inc*5)

In [ ]:
df[7698654:].shape

In [ ]:
df[0:7698654].to_csv('data/hn_cleaned_ready_for_bert_a.csv',index=False)

In [ ]:
df[7698654:].to_csv('data/hn_cleaned_ready_for_bert_b.csv',index=False)

In [5]:

import pandas as pd
import numpy as np

# IMPORT FROM CSV's
df = pd.read_csv('data/flocks_final_flocks_test_data_no_nans.csv')
df.head()

,id,comment_text,toxic,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,physical_disability,psychiatric_or_mental_illness,transgender,white,funny,wow,sad,likes,disagree,sexual_explicit
0,5736054,"As a constant, usually solo, wilderness wander...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.0
1,6116633,"Traditionally, in order for a papal teaching t...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.607634,0.89896,0.0
2,1084414,The idea that you would want to fill BC's vall...,0.2,0.0,0.0,0.0,0.0,0.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.0
3,486818,Really glad to see some justice brought for th...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.832874,0.00000,0.0
4,6280693,"""It's not about me. It's about how women, espe...",0.2,0.0,0.0,0.2,0.2,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.999718,1.0,0.0,0.550593,0.00000,0.0

In [3]:
df.head()

NameError: name 'df' is not defined

In [9]:

import pandas as pd
import numpy as np

# IMPORT FROM CSV's
df = pd.read_csv('data/flocks_final_flocks_train_data_no_nans.csv')
print(df.shape)

display(df.head())
df[0:5000].to_csv('data/train.csv',index=False)
df = df[["id", "comment_text"]]
df[5001:10000].to_csv('data/test.csv',index=False)

(303847, 38)

,id,comment_text,toxic,severe_toxicity,obscene,identity_attack,insult,threat,asian,atheist,...,physical_disability,psychiatric_or_mental_illness,transgender,white,funny,wow,sad,likes,disagree,sexual_explicit
0,5163696,"Outsider77, sometimes we just have to face the...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.649557,0.00000,0.0
1,6218480,"Right, just like an abused wife can seek recou...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.324505,0.00000,0.0
2,5699982,it obviously carried alot of weight in Denver....,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.4,0.000000,0.0,1.0,0.763469,0.00000,0.0
3,5146395,"Um, Mr Kelly, the game to which you refer was ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.999718,0.0,0.0,0.000000,0.00000,0.0
4,5987133,It sounds like a great idea - going after the ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.324505,0.89896,0.0

NameError: name 'df' is not defined